### ISSUE TITLE
Import opml fails

### ISSUE THREAD

**Issue by orschiro** [amatriain/feedbunch#16]
@amatriain! :-)

Love your reader, thanks! :-)

Ran into an issue. The following list of feeds would not import via opml import.

One by one import works though.

Any ideas?

Thanks!

```
http://www.gamersglobal.de/feeds/all
http://www.heise.de/ct/rss/artikel-atom.xml
http://www.reddit.com/r/Fedora/.rss
http://www.omgubuntu.co.uk/feed
https://rss.golem.de/rss.php?feed=RSS1.0
http://www.reddit.com/r/gnome/.rss
http://www.reddit.com/r/linux/.rss
https://www.computerbase.de/rss/news.xml
http://stadt-bremerhaven.de/feed/
https://www.heise.de/newsticker/heise-atom.xml
http://news.ycombinator.com/rss
```

![image](https://user-images.githubusercontent.com/170947/40497125-b34bec22-5f7b-11e8-8d29-8ef541ae57e9.png)

**Comment by orschiro** [comment]
@amatriain! :-)

Thanks so much for your support. :-)

Yes, now all looks good to me. 

Still, here is the opml file:

https://drive.google.com/file/d/1pObrpzOOpRLu1ZOEyR28N-cAHbdTtr8b/view?usp=sharing

Let me know!

**Comment by amatriain** [comment]
As I expected the OPML import now runs without issue. This confirms that the errors you got were fixed by the recent server upgrades.

Sorry for any inconvenience and thanks for your feedback. Let me know if I can help you further.

**Comment by orschiro** [comment]
Yes, will do and thanks to you for your immediate support! :-)
